spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playground?allowPublicKeyRetrieval=true&useSSL=false
    username: playground
    password: playground
    initialization-mode: always
    sql-script-encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
openapi:
  key: 6277564d6b746b6434385771656569