spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playground
    username: playground
    password: playground
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true